spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: wanghaocun
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_data
    username: root
    password: 123456
  jpa:
    show-sql: true
  cache:
    redis:
      time-to-live: 3600000

